apiVersion: v2
name: bitwardenrs
description: DEPRECATED - Unofficial Bitwarden compatible server written in Rust
type: application
version: 0.1.1
appVersion: 1.16.3
keywords:
  - bitwarden
  - bitwardenrs
  - bitwarden_rs
  - password
  - rust
home: https://github.com/billimek/billimek-charts/tree/master/charts/bitwarden_rs
sources:
  - https://github.com/dani-garcia/bitwarden_rs
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png
deprecated: true
