apiVersion: v1
appVersion: v2.6.1
description: DEPRECATED - ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home
name: grocy
version: 1.0.3
keywords:
  - grocy
home: https://github.com/billimek/billimek-charts/tree/master/charts/grocy
icon: https://github.com/grocy/grocy/raw/master/public/img/appicons/mstile-150x150.png
sources:
  - https://github.com/grocy/grocy
maintainers:
  - name: carpenike
    email: ryan@ryanholt.net
