apiVersion: v1
appVersion: v10.5.3-ls45
description: DEPRECATED - Jellyfin is a Free Software Media System
name: jellyfin
version: 1.0.4
keywords:
  - Jellyfin
  - mediaplayer
home: https://github.com/billimek/billimek-charts/tree/master/charts/Jellyfin
icon: https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/icon-solid-black.svg
sources:
  - https://hub.docker.com/r/linuxserver/Jellyfin/
  - https://github.com/Jellyfin/Jellyfin
deprecated: true
