apiVersion: v1
name: uptimerobot
version: 2.0.2
appVersion: 1.1.0
description: DEPRECATED - A tool to get statistics from Uptime Robot and log it into InfluxDB
keywords:
- uptimerobot
- influxdb
- grafana
home: https://github.com/billimek/billimek-charts/tree/master/charts/uptimerobot
icon: https://i.imgur.com/ARSSILk.png
sources:
- https://github.com/trojanc/node-influx-uptimerobot
- https://github.com/billimek/billimek-charts
deprecated: true
