apiVersion: v1
appVersion: "3.8.1"
description: DEPRECATED - Program for forwarding ADS-B data to FlightAware
name: piaware
version: 1.0.1
keywords:
  - piaware
  - flight-aware
  - flight-tracker
home: https://github.com/billimek/billimek-charts/tree/master/charts/piaware
icon: https://pbs.twimg.com/profile_images/964269455483088897/mr2UgvfG_400x400.jpg
sources:
  - https://github.com/flightaware/piaware
deprecated: true
