apiVersion: v1
name: comcast
version: 2.0.2
appVersion: 1.0.0
description: DEPRECATED - periodic comcast data usage checks and save the results to InfluxDB
keywords:
- comcast
- influxdb
- xfinity
home: https://github.com/billimek/billimek-charts/tree/master/charts/comcast
icon: https://i.imgur.com/iR1dUpp.png
sources:
- https://github.com/billimek/comcastUsage-for-influxdb
- https://github.com/billimek/billimek-charts
maintainers:
- name: billimek
  email: jeff@billimek.com
