apiVersion: v1
name: node-feature-discovery
version: 1.0.1
appVersion: 0.6.0
description: DEPRECATED - Detect hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels
keywords:
  - kubernetes
  - cluster
  - hardware
home: https://github.com/billimek/billimek-charts/tree/master/charts/node-feature-discovery
icon: https://avatars1.githubusercontent.com/u/36015203?s=400&v=4
sources:
  - https://github.com/kubernetes-sigs/node-feature-discovery
  - https://github.com/billimek/billimek-charts
deprecated: true
