apiVersion: v1
appVersion: 1.0.0
description: DEPRECATED - rtorrent and flood co-located in the same deployment
name: rtorrent-flood
version: 4.1.2
keywords:
  - rtorrent
  - flood
  - torrrent
home: https://github.com/billimek/billimek-charts/tree/master/charts/rtorrent-flood
icon: https://github.com/jfurrow/flood/blob/master/flood.png?raw=true
sources:
  - https://hub.docker.com/r/looselyrigorous/rtorrent
  - https://github.com/looselyrigorous/docker-rtorrent
  - https://github.com/Flood-UI/flood
deprecated: true
