apiVersion: v1
appVersion: "2.0.1"
description: DEPRECATED - Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus
name: unifi-poller
version: 1.0.2
keywords:
  - unifi
  - unifi-poller
home: https://github.com/billimek/billimek-charts/tree/master/charts/unifi-poller
icon: https://raw.githubusercontent.com/wiki/unifi-poller/unifi-poller/images/unifi-poller-logo.png
sources:
  - https://github.com/unifi-poller/unifi-poller
  - https://hub.docker.com/r/golift/unifi-poller
deprecated: true
