apiVersion: v1
appVersion: v21.0-ls14
description: DEPRECATED - NZBGet is a Usenet downloader client
name: nzbget
version: 3.3.3
keywords:
  - nzbget
  - usenet
home: https://github.com/billimek/billimek-charts/tree/master/charts/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/nzbget/
  - https://nzbget.net/
deprecated: true
