apiVersion: v1
appVersion: v0.2.0.1480-ls58
description: DEPRECATED - Radarr is a movie downloading client
name: radarr
version: 4.1.4
keywords:
  - radarr
  - usenet
  - bittorrent
home: https://github.com/billimek/billimek-charts/tree/master/charts/radarr
icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/radarr/
  - https://github.com/Radarr/Radarr/
deprecated: true
