apiVersion: v2
name: zigbee2mqtt
type: application
description: DEPRECATED - Bridges events and allows you to control your Zigbee devices via MQTT
appVersion: 1.14.1
version: 0.2.1
keywords:
  - zigbee
  - mqtt
home: https://www.zigbee2mqtt.io
icon: https://www.zigbee2mqtt.io/images/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
deprecated: true
