apiVersion: v1
appVersion: "3.0.0"
description: DEPRECATED - Fully configurable Zwave to MQTT gateway and Control Panel using NodeJS and Vue
name: zwave2mqtt
version: 2.1.1
keywords:
  - zwave
  - mqtt
  - home-assistant
home: https://github.com/billimek/billimek-charts/tree/master/charts/zwave2mqtt
icon: https://github.com/OpenZWave/Zwave2Mqtt/raw/master/docs/OZW_Logo.png
sources:
  - https://github.com/OpenZWave/Zwave2Mqtt
deprecated: true
