apiVersion: v1
appVersion: v2.22.2-ls9
description: DEPRECATED - Usenet meta search
name: nzbhydra2
version: 2.3.3
keywords:
  - nzbhydra2
  - usenet
home: https://github.com/billimek/billimek-charts/tree/master/charts/nzbhydra2
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hydra-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/nzbhydra2/
  - https://github.com/theotherp/nzbhydra2
deprecated: true
