apiVersion: v2
appVersion: 0.3.0
version: 0.1.1
name: icantbelieveitsnotvaletudo
description: DEPRECATED - Create live map data from Valetudo powered robots
type: application
keywords:
  - MQTT
  - valetudo
  - iot
home: https://valetudo.cloud
sources:
  - https://github.com/Hypfer/ICantBelieveItsNotValetudo
deprecated: true
